### ISSUE TITLE
Funny messages with read_result

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/JACUSA2helper#10]
SIIIRTMg=read_result("rmDup_SIIIRTMg_RC22_rtarrest_plain_result.out")
Warnmeldungen:
1: In for (n in impnames) if (!is.null(genImp <- impenv[[n]])) { :
  ungenutzte Verbindung 6 (rmDup_HIVRT_RC22_rtarrest_plain_result.out) geschlossen
2: In for (n in impnames) if (!is.null(genImp <- impenv[[n]])) { :
  ungenutzte Verbindung 5 (rmDup_HIVRT_RC22_rtarrest_plain_result.out) geschlossen
3: In for (n in impnames) if (!is.null(genImp <- impenv[[n]])) { :
  ungenutzte Verbindung 4 (rmDup_HIVRT_RC22_rtarrest_plain_result.out) geschlossen
4: In for (n in impnames) if (!is.null(genImp <- impenv[[n]])) { :
  ungenutzte Verbindung 3 (rmDup_HIVRT_RC22_rtarrest_plain_result.out) geschlossen

I dont know why these warning appear.

**Comment by piechottam** [comment]
I cannot verify - does it happen in a "fresh" R session?

**Comment by CDieterich** [comment]
Nope, I think that does not happen in a fresh R session.. just confirmed.
