### ISSUE TITLE
lapply_cond

### ISSUE THREAD

**Issue by XRCHAM** [dieterich-lab/JACUSA2helper#18]
Hi there,

I just updated my Rstudio, and redo some data analysis. And I found I could not use the lapply_cond function with the error as below:

`rdd[["bc"]] <- lapply_cond(rdd$bases, function(b) { Reduce("+", b) } ) %>% Reduce("+", .) %>% base_count()`
**Error in .wrap_in_length_one_list_like_object(value, name, x) : 
  failed to coerce 'list(value)' to a GRanges object of length 1**

And here is the package I installed(R4.2.0):
```
install.packages("devtools")
library(devtools)
library(GenomicRanges)
library(dplyr)
install_github("dieterich-lab/JACUSA2helper")
library(JACUSA2helper)
library(magrittr)
set.seed(777)

```
when I changed the script like below, it works!
##OLD  with error
`rdd[["bc"]] <- lapply_cond(rdd$bases, function(b) { Reduce("+", b) } ) %>% Reduce("+", .) %>% base_count()
`
##NEW
`rdd$bc <- lapply_cond(rdd$bases, function(b) { Reduce("+", b) } ) %>% Reduce("+", .) %>% base_count()
`
but I got another problem:
```
rdd.filter <- rdd %>%
  dplyr::filter(bc <= 3)
```

Error in UseMethod("filter") : 
  no applicable method for 'filter' applied to an object of class "c('GRanges', 'GenomicRanges', 'Ranges', 'GenomicRanges_OR_missing', 'GenomicRanges_OR_GenomicRangesList', 'GenomicRanges_OR_GRangesList', 'List', 'Vector', 'list_OR_List', 'Annotated', 'vector_OR_Vector')"

Thanks!

**Comment by piechottam** [comment]
Sry, for the delay.
It seems that package [plyranges](https://www.bioconductor.org/packages/release/bioc/html/plyranges.html) is not installed or loaded. 

After installing JACUSA2helper from github you might need to run
```R
devtools::install_deps("JACUSA2helper")
```

**Comment by XRCHAM** [comment]
It works and I just closed the issue. Thanks!

Best,
Xiangbin

On Aug 25, 2022, at 10:01 AM, Michael Piechotta ***@***.******@***.***>> wrote:



Sry, for the delay.
It seems that package plyranges<https://urldefense.com/v3/__https://www.bioconductor.org/packages/release/bioc/html/plyranges.html__;!!BpyFHLRN4TMTrA!64y5H-yR0r-rmUAHwrgG146sLgJLvl0jKf7sRU1Ankevbo6NhAm0VRlXSfBrsgkX98PVecqhw_2ko9eDXTE3DQH-KMOTbTU$> is not installed or loaded.

After installing JACUSA2helper from github you might need to run

devtools::install_deps("JACUSA2helper")
